# Generated by Django 4.1.2 on 2022-10-29 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='songId',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artisteId',
        ),
        migrations.AddField(
            model_name='lyric',
            name='song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music_app.song'),
            preserve_default=False,
        ),
    ]
